# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(choices=[(0.25, '1/4'), (0.5, '1/2'), (0.75, '3/4'), (1.0, '1')])),
                ('origin', models.IntegerField(choices=[(0, 'Llegada tarde'), (1, 'Retiro anticipado')])),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Registro')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='absence',
            name='student',
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
        migrations.AddField(
            model_name='justified',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Relation'),
        ),
    ]
