# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0002_auto_20180526_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='origin',
            field=models.IntegerField(blank=True, choices=[(0, 'Llegada tarde'), (1, 'Retiro anticipado')]),
        ),
        migrations.AlterField(
            model_name='relation',
            name='percentage',
            field=models.FloatField(blank=True, choices=[(0.25, '1/4'), (0.5, '1/2'), (0.75, '3/4'), (1.0, '1')]),
        ),
    ]
