# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0004_auto_20180526_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justified',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='preceptor',
        ),
        migrations.AddField(
            model_name='registro',
            name='preceptor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Preceptor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='justified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parent',
            name='childs',
            field=models.ManyToManyField(related_name='parents', to='controlAsistencia.Student'),
        ),
        migrations.AlterField(
            model_name='preceptor',
            name='year',
            field=models.ManyToManyField(related_name='preceptores', to='controlAsistencia.Year'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='origin',
            field=models.IntegerField(choices=[(0, 'Llegada tarde'), (1, 'Retiro anticipado')]),
        ),
        migrations.AlterField(
            model_name='relation',
            name='percentage',
            field=models.FloatField(choices=[(0.25, '1/4'), (0.5, '1/2'), (0.75, '3/4'), (1.0, '1')]),
        ),
        migrations.AlterField(
            model_name='relation',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Registro'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Student'),
        ),
        migrations.DeleteModel(
            name='Justified',
        ),
    ]
