# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year_number',
            field=models.IntegerField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Septimo')]),
        ),
    ]
