# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='food_obvs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
