# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0002_auto_20180621_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
