# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0002_auto_20180621_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('percentage', models.FloatField(choices=[(0.25, '1/4'), (0.5, '1/2'), (0.75, '3/4'), (1.0, '1')])),
                ('origin', models.IntegerField(choices=[(0, 'Llegada tarde'), (1, 'Retiro anticipado')])),
                ('justified', models.BooleanField(default=False)),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Preceptor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Year')),
            ],
        ),
        migrations.RemoveField(
            model_name='registro',
            name='preceptor',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='year',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='student',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
