# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0003_auto_20180526_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='registro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Registro'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='controlAsistencia.Student'),
        ),
    ]
