# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0004_auto_20180510_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='preceptor',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
