# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-04 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0005_auto_20180529_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preceptor',
            name='year',
            field=models.ManyToManyField(blank=True, related_name='preceptores', to='controlAsistencia.Year'),
        ),
    ]
