# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencia', '0006_auto_20180604_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preceptor',
            name='year',
            field=models.ManyToManyField(blank=True, null=True, related_name='preceptores', to='controlAsistencia.Year'),
        ),
    ]
